server:
  port: 6000
  host: localhost

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/redistest
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${server.host}:3306/redis_test_db
    username: root
    password: 1219
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true 
  cache:
    type: redis
  redis:
    host: ${server.host}
    port: 6379